In [1]:
import numpy as np

In [56]:
w = np.array([1,2,3])
w_history = []
for i in range(5):
    w = w + np.random.normal(size=3)
    w_history.append(w)


In [59]:
w_history

[array([2.48134179, 2.31115579, 3.5229736 ]),
 array([2.80323706, 0.87222935, 3.44755956]),
 array([2.81657695, 1.25433455, 3.69044516]),
 array([3.37790498, 1.37615128, 3.92184196]),
 array([3.57271811, 0.50373914, 3.08184818])]

In [58]:
np.random.normal(size=3)

array([ 0.89644622, -0.10266471, -0.2182981 ])

In [ ]:
l = [1,2,3]