- 3장까지는 피자의 지름처럼 설명 변수가 실수 값을 가지는 케이스였다.

In [1]:
from sklearn.feature_extraction import DictVectorizer
onehot_encoder = DictVectorizer()

In [2]:
X = [
    {'city': 'New York'},
    {'city': 'San Fancisco'},
    {'city': 'Chapel Hill'}
]
print(onehot_encoder.fit_transform(X).toarray())

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


# 1. 특징의 표준화

In [3]:
from sklearn import preprocessing
import numpy as np
X = np.array([
    [0.,0.,5.,13.,9.,1.],
    [0.,0.,13.,15.,10.,15.],
    [0.,3.,15.,2.,0.,11.]
])

In [4]:
print(preprocessing.scale(X))

[[ 0.         -0.70710678 -1.38873015  0.52489066  0.59299945 -1.35873244]
 [ 0.         -0.70710678  0.46291005  0.87481777  0.81537425  1.01904933]
 [ 0.          1.41421356  0.9258201  -1.39970842 -1.4083737   0.33968311]]
